### ISSUE TITLE
Support for deployment outside of GCP

### ISSUE THREAD

**Issue by Ferdy89** [trotto/go-links#14]
Hi! I love Trotto, thank you for making it open source!

Today I installed Trotto on a Raspberry Pi, but it was a bit complicated, mainly because of the tight coupling the current code has with GCP. I had to work around a handful of issues until I managed to get it to work.

I wonder if that kind of support is something that interests you. If so, I can try to put some effort into polishing those workarounds and make some Pull Requests.

If not, I completely understand! I'll keep the hacks to myself :stuck_out_tongue_closed_eyes:

**Comment by itsojon** [comment]
Hey @Ferdy89! Thank you, and you're so welcome!

That is rad that you put it on a Pi! I'm pretty sure you're breaking new ground there! 😹 

Decoupling from GCP is indeed a high priority for Trotto, since GCP doesn't suit every use case. I did some initial work on this last year in https://github.com/trotto/go-links/tree/jon/platform_agnostic, but never finished it up. I'd love to collaborate on getting it done. The approach I took was to consolidate all datastore interactions to a single package ([here](https://github.com/trotto/go-links/tree/jon/platform_agnostic/server/src/modules/data)) and implement a common interface for each datastore. Then you'd specify which implementation to use in a config file. To prove it out, I tried SQLite, but I imagine supporting at most 3 datastores would suffice for the future (Cloud Datastore, PostgreSQL or similar, and maybe just file system for the most dead-simple (if unreliable) implementation). Maintaining support for multiple databases certainly adds overhead, but the goal is to keep the Trotto core nice and simple, so there won't be a frequent need to implement new datastore interactions for multiple stores.

I welcome your thoughts on that approach and would love to hear how it compares to what you did!

**Comment by itsojon** [comment]
@Ferdy89 hope you're well! I'm pleased to say we've moved Trotto to a platform-agnostic stack, using Postgres as the database. We've documented how to deploy with Docker as well as how to deploy to Heroku, which is quite simple since Heroku can create a Postgres database automatically:

- [Deploy with Docker](https://www.trot.to/docs/deploy/deploy-with-docker)
- [Deploy to Heroku](https://www.trot.to/docs/deploy/deploy-to-heroku)

Take a look and please let me know if you have any questions!

**Comment by Mistic92** [comment]
Hi, so now it's not possible to run with Datastore?
