### ISSUE TITLE
missing file for local dev setup

### ISSUE THREAD

**Issue by llwp** [trotto/go-links#19]
appears as if there is a missing file at this time;
https://github.com/trotto/go-links/blob/master/server/run_local.sh#L5

`dev_appserver.py` does not exist in master branch.

**Comment by itsojon** [comment]
Thank you for checking out Trotto, @llwp! And thank you for working through the issue with me over chat.

Since the issue was ultimately the Python version, I've updated the documentation to recommend using `virtualenv` or `pyenv` with the minimum Python 2 version needed for the `dev_appserver.py` command when running locally.
